version: "3"

services:
  vpn:
    image: bubuntux/nordvpn
    container_name: vpn
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=test@email.com
      - PASS='P@ssw0rd'
      - COUNTRY=Germany
      - PROTOCOL=UDP
      - CATEGORY=P2P
      - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 180
    ports:
      - 9090:9090
      - 6881:6881
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    depends_on:
      - vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
      - WEBUI_PORT=9090
    network_mode: service:vpn
    volumes:
      - $PWD/config:/config
      - $PWD/downloads:/downloads
    restart: unless-stopped
